const STORE='siddhi_hostel_data_v1', SETTINGS='siddhi_hostel_settings_v1';
const today=()=>new Date().toISOString().slice(0,10);
const seed={rooms:[{roomNumber:'101',floor:'1',roomType:'Double Sharing',totalBeds:2,monthlyRent:4500,status:'Full'},{roomNumber:'102',floor:'1',roomType:'Triple Sharing',totalBeds:3,monthlyRent:3800,status:'Available'},{roomNumber:'201',floor:'2',roomType:'Four Sharing',totalBeds:4,monthlyRent:3200,status:'Available'}],students:[{studentId:'STU1001',studentName:'Amit Meena',fatherName:'Ramesh Meena',mobile:'9876543210',parentMobile:'9898989898',course:'B.Sc. Nursing',semester:'2nd Semester',roomNumber:'101',bedNumber:'B1',joiningDate:today(),monthlyFee:4500,securityDeposit:5000,status:'Active',address:''},{studentId:'STU1002',studentName:'Ravi Kumar',fatherName:'Mohan Kumar',mobile:'9876500000',parentMobile:'9898900000',course:'B.Sc. Nursing',semester:'2nd Semester',roomNumber:'101',bedNumber:'B2',joiningDate:today(),monthlyFee:4500,securityDeposit:5000,status:'Active',address:''}],fees:[{receiptId:'RCPT1001',studentId:'STU1001',studentName:'Amit Meena',date:today(),feeMonth:today().slice(0,7),amount:4500,method:'UPI',type:'Monthly Fee',remarks:''}],attendance:[],visitors:[],complaints:[{complaintId:'CMP1001',studentId:'STU1002',studentName:'Ravi Kumar',roomNumber:'101',category:'Wi-Fi',description:'Internet not working',priority:'Medium',status:'Open',date:today()}]};
let db=JSON.parse(localStorage.getItem(STORE)||'null')||structuredClone(seed);
let settings=JSON.parse(localStorage.getItem(SETTINGS)||'null')||{scriptUrl:'',hostelWhatsApp:'',hostelAddress:''};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function save(){localStorage.setItem(STORE,JSON.stringify(db));renderAll()}
function toast(m){let t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function badge(v){return `<span class="badge ${String(v).replaceAll(' ','-')}">${v}</span>`}
async function api(action,payload={}){if(!settings.scriptUrl)return null;let r=await fetch(settings.scriptUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});let d=await r.json();if(!d.ok)throw new Error(d.error||'API error');return d.data}

document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();if(username.value==='admin'&&password.value==='admin123'){loginScreen.classList.add('hidden');app.classList.remove('hidden');renderAll()}else toast('Invalid login')};
logoutBtn.onclick=()=>location.reload();dateLabel.textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+id).classList.add('active-view');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));pageTitle.textContent=id[0].toUpperCase()+id.slice(1)}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.open).showModal());

function occupiedBeds(){return db.students.filter(s=>s.status==='Active').length}
function renderDashboard(){let beds=db.rooms.reduce((s,r)=>s+Number(r.totalBeds),0),occ=occupiedBeds(),vac=Math.max(0,beds-occ),col=db.fees.reduce((s,f)=>s+Number(f.amount),0),due=db.students.filter(s=>s.status==='Active').reduce((s,x)=>s+Number(x.monthlyFee),0)-db.fees.filter(f=>f.type==='Monthly Fee'&&f.feeMonth===today().slice(0,7)).reduce((s,f)=>s+Number(f.amount),0);kpiStudents.textContent=db.students.filter(s=>s.status==='Active').length;kpiBeds.textContent=beds;kpiVacant.textContent=vac;kpiOccupied.textContent=occ;kpiCollected.textContent=money(col);kpiPending.textContent=money(Math.max(0,due));let p=beds?Math.round(occ/beds*100):0;occupancyBar.innerHTML=`<div class="bar-label"><span>${occ} occupied of ${beds}</span><strong>${p}%</strong></div><div class="bar"><span style="width:${p}%"></span></div>`;recentStudents.innerHTML=db.students.slice().reverse().slice(0,5).map(s=>`<tr><td>${s.studentId}</td><td>${s.studentName}</td><td>${s.course}</td><td>${s.roomNumber}</td><td>${s.bedNumber}</td><td>${s.mobile}</td><td>${badge(s.status)}</td></tr>`).join('')}
function renderStudents(filter=''){let f=filter.toLowerCase();studentsBody.innerHTML=db.students.filter(s=>JSON.stringify(s).toLowerCase().includes(f)).map(s=>`<tr><td>${s.studentId}</td><td>${s.studentName}</td><td>${s.fatherName}</td><td>${s.course}</td><td>${s.mobile}</td><td>${s.roomNumber}</td><td>${s.bedNumber}</td><td>${s.joiningDate}</td><td>${badge(s.status)}</td><td><button class="action-link" onclick="whatsappParent('${s.studentId}')">WhatsApp</button></td></tr>`).join('')}
studentSearch.oninput=e=>renderStudents(e.target.value);
function renderRooms(){roomsGrid.innerHTML=db.rooms.map(r=>{let students=db.students.filter(s=>s.roomNumber===r.roomNumber&&s.status==='Active'),beds=Array.from({length:Number(r.totalBeds)},(_,i)=>{let st=students.find(s=>s.bedNumber===`B${i+1}`);return `<div class="bed ${st?'occupied':''}" title="${st?.studentName||'Vacant'}">B${i+1}</div>`}).join('');return `<article class="room-card"><div class="room-top"><div><div class="room-number">${r.roomNumber}</div><div class="room-meta">Floor ${r.floor} • ${r.roomType}</div></div>${badge(students.length>=Number(r.totalBeds)?'Full':'Available')}</div><div>${money(r.monthlyRent)} / month</div><div class="bed-grid">${beds}</div></article>`}).join('')}
function renderFees(){feesBody.innerHTML=db.fees.slice().reverse().map(f=>`<tr><td>${f.receiptId}</td><td>${f.studentName}</td><td>${f.date}</td><td>${f.feeMonth}</td><td>${money(f.amount)}</td><td>${f.method}</td><td>${f.type}</td><td>${f.remarks||'-'}</td></tr>`).join('')}
function renderAttendance(){attendanceDate.value=attendanceDate.value||today();attendanceBody.innerHTML=db.students.filter(s=>s.status==='Active').map(s=>`<tr><td>${s.studentName}</td><td>${s.roomNumber}</td><td><select id="att-${s.studentId}"><option>Present</option><option>Absent</option><option>Leave</option><option>Out Pass</option></select></td><td><input type="time" id="in-${s.studentId}"></td><td><input type="time" id="out-${s.studentId}"></td><td><button class="secondary" onclick="saveAttendance('${s.studentId}')">Save</button></td></tr>`).join('')}
function renderVisitors(){visitorsBody.innerHTML=db.visitors.slice().reverse().map(v=>`<tr><td>${v.visitorId}</td><td>${v.visitorName}</td><td>${v.studentName}</td><td>${v.relation||'-'}</td><td>${v.date}</td><td>${v.inTime}</td><td>${v.outTime||'-'}</td><td>${v.mobile||'-'}</td></tr>`).join('')}
function renderComplaints(){complaintsBody.innerHTML=db.complaints.slice().reverse().map(c=>`<tr><td>${c.complaintId}</td><td>${c.studentName}</td><td>${c.roomNumber}</td><td>${c.category}</td><td>${c.description}</td><td>${badge(c.priority)}</td><td>${badge(c.status)}</td><td><button class="action-link" onclick="resolveComplaint('${c.complaintId}')">Resolve</button></td></tr>`).join('')}
function renderSelects(){let opts=db.students.filter(s=>s.status==='Active').map(s=>`<option value="${s.studentId}">${s.studentId} - ${s.studentName}</option>`).join('');feeStudent.innerHTML='<option value="">Select student</option>'+opts;visitorStudent.innerHTML='<option value="">Select student</option>'+opts;complaintStudent.innerHTML='<option value="">Select student</option>'+opts;studentRoom.innerHTML='<option value="">Select room</option>'+db.rooms.map(r=>`<option>${r.roomNumber}</option>`).join('');renderBeds()}
studentRoom.onchange=renderBeds;function renderBeds(){let r=db.rooms.find(x=>x.roomNumber===studentRoom.value);if(!r){studentBed.innerHTML='<option value="">Select bed</option>';return}let used=db.students.filter(s=>s.roomNumber===r.roomNumber&&s.status==='Active').map(s=>s.bedNumber);studentBed.innerHTML='<option value="">Select bed</option>'+Array.from({length:Number(r.totalBeds)},(_,i)=>`B${i+1}`).filter(b=>!used.includes(b)).map(b=>`<option>${b}</option>`).join('')}
function renderAll(){renderDashboard();renderStudents();renderRooms();renderFees();renderAttendance();renderVisitors();renderComplaints();renderSelects();scriptUrl.value=settings.scriptUrl||'';hostelWhatsApp.value=settings.hostelWhatsApp||'';hostelAddress.value=settings.hostelAddress||''}

studentForm.onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));let row={studentId:'STU'+Date.now().toString().slice(-7),studentName:f.studentName,fatherName:f.fatherName,mobile:f.mobile,parentMobile:f.parentMobile,course:f.course,semester:f.semester,roomNumber:f.roomNumber,bedNumber:f.bedNumber,joiningDate:f.joiningDate,monthlyFee:Number(f.monthlyFee),securityDeposit:Number(f.securityDeposit||0),status:f.status,address:f.address};db.students.push(row);save();e.target.reset();studentModal.close();toast('Student added');try{await api('createStudent',row)}catch(err){toast('Saved locally; sheet sync failed')}}
roomForm.onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));let row={roomNumber:f.roomNumber,floor:f.floor,roomType:f.roomType,totalBeds:Number(f.totalBeds),monthlyRent:Number(f.monthlyRent),status:f.status};db.rooms.push(row);save();e.target.reset();roomModal.close();toast('Room added');try{await api('createRoom',row)}catch(err){}}
feeForm.onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),s=db.students.find(x=>x.studentId===f.studentId);let row={receiptId:'RCPT'+Date.now().toString().slice(-7),studentId:f.studentId,studentName:s?.studentName||'',date:today(),feeMonth:f.feeMonth,amount:Number(f.amount),method:f.method,type:f.type,remarks:f.remarks};db.fees.push(row);save();e.target.reset();feeModal.close();toast('Fee saved');try{await api('createFee',row)}catch(err){}}
visitorForm.onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),s=db.students.find(x=>x.studentId===f.studentId);let row={visitorId:'VIS'+Date.now().toString().slice(-7),visitorName:f.visitorName,studentId:f.studentId,studentName:s?.studentName||'',relation:f.relation,mobile:f.mobile,date:today(),inTime:f.inTime,outTime:'',purpose:f.purpose};db.visitors.push(row);save();e.target.reset();visitorModal.close();toast('Visitor entry saved');try{await api('createVisitor',row)}catch(err){}}
complaintForm.onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),s=db.students.find(x=>x.studentId===f.studentId);let row={complaintId:'CMP'+Date.now().toString().slice(-7),studentId:f.studentId,studentName:s?.studentName||'',roomNumber:s?.roomNumber||'',category:f.category,description:f.description,priority:f.priority,status:f.status,date:today()};db.complaints.push(row);save();e.target.reset();complaintModal.close();toast('Complaint saved');try{await api('createComplaint',row)}catch(err){}}
saveSettings.onclick=()=>{settings={scriptUrl:scriptUrl.value.trim(),hostelWhatsApp:hostelWhatsApp.value.trim(),hostelAddress:hostelAddress.value.trim()};localStorage.setItem(SETTINGS,JSON.stringify(settings));toast('Settings saved')}
syncBtn.onclick=async()=>{if(!settings.scriptUrl){switchView('settings');toast('Add Apps Script URL first');return}try{let data=await api('getAll');if(data){db=data;save();toast('Google Sheet synced')}}catch(e){toast('Sync failed: '+e.message)}}
markAllPresent.onclick=()=>document.querySelectorAll('[id^="att-"]').forEach(x=>x.value='Present');
window.saveAttendance=async id=>{let s=db.students.find(x=>x.studentId===id),row={attendanceId:'ATT'+Date.now().toString().slice(-7),date:attendanceDate.value,studentId:id,studentName:s.studentName,roomNumber:s.roomNumber,status:document.querySelector('#att-'+id).value,inTime:document.querySelector('#in-'+id).value,outTime:document.querySelector('#out-'+id).value};db.attendance.push(row);save();toast('Attendance saved');try{await api('createAttendance',row)}catch(e){}}
window.resolveComplaint=async id=>{let c=db.complaints.find(x=>x.complaintId===id);c.status='Resolved';save();toast('Complaint resolved');try{await api('updateComplaint',c)}catch(e){}}
window.whatsappParent=id=>{let s=db.students.find(x=>x.studentId===id),num=String(s.parentMobile||s.mobile).replace(/\D/g,'').slice(-10),msg=`Namaste,\n\n${s.studentName} ke hostel record ke sambandh me Siddhi Hostel se sampark kiya ja raha hai.\nRoom: ${s.roomNumber}, Bed: ${s.bedNumber}\n\nThank you,\nSiddhi Hostel`;window.open(`https://wa.me/91${num}?text=${encodeURIComponent(msg)}`,'_blank')}
renderAll();